<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TiendaMaestroPlanificacion', 'doctrine');

/**
 * BaseTiendaMaestroPlanificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresas_id
 * @property float $total_planificacion
 * @property timestamp $fecha_planificacion
 * @property Empresas $Empresas
 * @property Doctrine_Collection $TiendaDetallePlanificacion
 * 
 * @method integer                    getId()                         Returns the current record's "id" value
 * @method integer                    getEmpresasId()                 Returns the current record's "empresas_id" value
 * @method float                      getTotalPlanificacion()         Returns the current record's "total_planificacion" value
 * @method timestamp                  getFechaPlanificacion()         Returns the current record's "fecha_planificacion" value
 * @method Empresas                   getEmpresas()                   Returns the current record's "Empresas" value
 * @method Doctrine_Collection        getTiendaDetallePlanificacion() Returns the current record's "TiendaDetallePlanificacion" collection
 * @method TiendaMaestroPlanificacion setId()                         Sets the current record's "id" value
 * @method TiendaMaestroPlanificacion setEmpresasId()                 Sets the current record's "empresas_id" value
 * @method TiendaMaestroPlanificacion setTotalPlanificacion()         Sets the current record's "total_planificacion" value
 * @method TiendaMaestroPlanificacion setFechaPlanificacion()         Sets the current record's "fecha_planificacion" value
 * @method TiendaMaestroPlanificacion setEmpresas()                   Sets the current record's "Empresas" value
 * @method TiendaMaestroPlanificacion setTiendaDetallePlanificacion() Sets the current record's "TiendaDetallePlanificacion" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiendaMaestroPlanificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tienda_maestro_planificacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tienda_maestro_planificacion_id',
             'length' => 4,
             ));
        $this->hasColumn('empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('total_planificacion', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_planificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'now()',
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresas', array(
             'local' => 'empresas_id',
             'foreign' => 'id'));

        $this->hasMany('TiendaDetallePlanificacion', array(
             'local' => 'id',
             'foreign' => 'tienda_maestro_planificacion_id'));
    }
}