<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estados', 'doctrine');

/**
 * BaseEstados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $nombre
 * @property Doctrine_Collection $Municipios
 * 
 * @method string              getId()         Returns the current record's "id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method Doctrine_Collection getMunicipios() Returns the current record's "Municipios" collection
 * @method Estados             setId()         Sets the current record's "id" value
 * @method Estados             setNombre()     Sets the current record's "nombre" value
 * @method Estados             setMunicipios() Sets the current record's "Municipios" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados');
        $this->hasColumn('id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Municipios', array(
             'local' => 'id',
             'foreign' => 'estados_id'));
    }
}