<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TiendaDetallePedido', 'doctrine');

/**
 * BaseTiendaDetallePedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $productos_id
 * @property float $cantidad
 * @property date $fecha_entrega
 * @property integer $tienda_maestro_pedido_id
 * @property TiendaMaestroPedido $TiendaMaestroPedido
 * @property Productos $Productos
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method integer             getProductosId()              Returns the current record's "productos_id" value
 * @method float               getCantidad()                 Returns the current record's "cantidad" value
 * @method date                getFechaEntrega()             Returns the current record's "fecha_entrega" value
 * @method integer             getTiendaMaestroPedidoId()    Returns the current record's "tienda_maestro_pedido_id" value
 * @method TiendaMaestroPedido getTiendaMaestroPedido()      Returns the current record's "TiendaMaestroPedido" value
 * @method Productos           getProductos()                Returns the current record's "Productos" value
 * @method TiendaDetallePedido setId()                       Sets the current record's "id" value
 * @method TiendaDetallePedido setProductosId()              Sets the current record's "productos_id" value
 * @method TiendaDetallePedido setCantidad()                 Sets the current record's "cantidad" value
 * @method TiendaDetallePedido setFechaEntrega()             Sets the current record's "fecha_entrega" value
 * @method TiendaDetallePedido setTiendaMaestroPedidoId()    Sets the current record's "tienda_maestro_pedido_id" value
 * @method TiendaDetallePedido setTiendaMaestroPedido()      Sets the current record's "TiendaMaestroPedido" value
 * @method TiendaDetallePedido setProductos()                Sets the current record's "Productos" value
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiendaDetallePedido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tienda_detalle_pedido');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('productos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_entrega', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('tienda_maestro_pedido_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TiendaMaestroPedido', array(
             'local' => 'tienda_maestro_pedido_id',
             'foreign' => 'id'));

        $this->hasOne('Productos', array(
             'local' => 'productos_id',
             'foreign' => 'id'));
    }
}