<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Empresas', 'doctrine');

/**
 * BaseEmpresas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_empresa
 * @property string $actividad_economica
 * @property string $rif
 * @property string $direccion
 * @property string $localidad
 * @property string $coordenada_x
 * @property string $coordenada_y
 * @property integer $ejes_id
 * @property integer $ambitos_id
 * @property string $parroquias_id
 * @property integer $tipo_empresas_id
 * @property integer $status_empresas_id
 * @property boolean $bicentenario
 * @property TipoEmpresas $TipoEmpresas
 * @property StatusEmpresas $StatusEmpresas
 * @property Parroquias $Parroquias
 * @property Ejes $Ejes
 * @property Ambitos $Ambitos
 * @property Doctrine_Collection $Categorias
 * @property Doctrine_Collection $Clientes
 * @property Doctrine_Collection $Devoluciones
 * @property Doctrine_Collection $PlanificacionMaestros
 * @property Doctrine_Collection $Productos
 * @property Doctrine_Collection $TiendaMaestroPedido
 * @property Doctrine_Collection $VentasMaestro
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getNombreEmpresa()         Returns the current record's "nombre_empresa" value
 * @method string              getActividadEconomica()    Returns the current record's "actividad_economica" value
 * @method string              getRif()                   Returns the current record's "rif" value
 * @method string              getDireccion()             Returns the current record's "direccion" value
 * @method string              getLocalidad()             Returns the current record's "localidad" value
 * @method string              getCoordenadaX()           Returns the current record's "coordenada_x" value
 * @method string              getCoordenadaY()           Returns the current record's "coordenada_y" value
 * @method integer             getEjesId()                Returns the current record's "ejes_id" value
 * @method integer             getAmbitosId()             Returns the current record's "ambitos_id" value
 * @method string              getParroquiasId()          Returns the current record's "parroquias_id" value
 * @method integer             getTipoEmpresasId()        Returns the current record's "tipo_empresas_id" value
 * @method integer             getStatusEmpresasId()      Returns the current record's "status_empresas_id" value
 * @method boolean             getBicentenario()          Returns the current record's "bicentenario" value
 * @method TipoEmpresas        getTipoEmpresas()          Returns the current record's "TipoEmpresas" value
 * @method StatusEmpresas      getStatusEmpresas()        Returns the current record's "StatusEmpresas" value
 * @method Parroquias          getParroquias()            Returns the current record's "Parroquias" value
 * @method Ejes                getEjes()                  Returns the current record's "Ejes" value
 * @method Ambitos             getAmbitos()               Returns the current record's "Ambitos" value
 * @method Doctrine_Collection getCategorias()            Returns the current record's "Categorias" collection
 * @method Doctrine_Collection getClientes()              Returns the current record's "Clientes" collection
 * @method Doctrine_Collection getDevoluciones()          Returns the current record's "Devoluciones" collection
 * @method Doctrine_Collection getPlanificacionMaestros() Returns the current record's "PlanificacionMaestros" collection
 * @method Doctrine_Collection getProductos()             Returns the current record's "Productos" collection
 * @method Doctrine_Collection getTiendaMaestroPedido()   Returns the current record's "TiendaMaestroPedido" collection
 * @method Doctrine_Collection getVentasMaestro()         Returns the current record's "VentasMaestro" collection
 * @method Empresas            setId()                    Sets the current record's "id" value
 * @method Empresas            setNombreEmpresa()         Sets the current record's "nombre_empresa" value
 * @method Empresas            setActividadEconomica()    Sets the current record's "actividad_economica" value
 * @method Empresas            setRif()                   Sets the current record's "rif" value
 * @method Empresas            setDireccion()             Sets the current record's "direccion" value
 * @method Empresas            setLocalidad()             Sets the current record's "localidad" value
 * @method Empresas            setCoordenadaX()           Sets the current record's "coordenada_x" value
 * @method Empresas            setCoordenadaY()           Sets the current record's "coordenada_y" value
 * @method Empresas            setEjesId()                Sets the current record's "ejes_id" value
 * @method Empresas            setAmbitosId()             Sets the current record's "ambitos_id" value
 * @method Empresas            setParroquiasId()          Sets the current record's "parroquias_id" value
 * @method Empresas            setTipoEmpresasId()        Sets the current record's "tipo_empresas_id" value
 * @method Empresas            setStatusEmpresasId()      Sets the current record's "status_empresas_id" value
 * @method Empresas            setBicentenario()          Sets the current record's "bicentenario" value
 * @method Empresas            setTipoEmpresas()          Sets the current record's "TipoEmpresas" value
 * @method Empresas            setStatusEmpresas()        Sets the current record's "StatusEmpresas" value
 * @method Empresas            setParroquias()            Sets the current record's "Parroquias" value
 * @method Empresas            setEjes()                  Sets the current record's "Ejes" value
 * @method Empresas            setAmbitos()               Sets the current record's "Ambitos" value
 * @method Empresas            setCategorias()            Sets the current record's "Categorias" collection
 * @method Empresas            setClientes()              Sets the current record's "Clientes" collection
 * @method Empresas            setDevoluciones()          Sets the current record's "Devoluciones" collection
 * @method Empresas            setPlanificacionMaestros() Sets the current record's "PlanificacionMaestros" collection
 * @method Empresas            setProductos()             Sets the current record's "Productos" collection
 * @method Empresas            setTiendaMaestroPedido()   Sets the current record's "TiendaMaestroPedido" collection
 * @method Empresas            setVentasMaestro()         Sets the current record's "VentasMaestro" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpresas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'empresas_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre_empresa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('actividad_economica', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('rif', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('localidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('coordenada_x', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('coordenada_y', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ejes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ambitos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('parroquias_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('status_empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('bicentenario', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'false',
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoEmpresas', array(
             'local' => 'tipo_empresas_id',
             'foreign' => 'id'));

        $this->hasOne('StatusEmpresas', array(
             'local' => 'status_empresas_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquias', array(
             'local' => 'parroquias_id',
             'foreign' => 'id'));

        $this->hasOne('Ejes', array(
             'local' => 'ejes_id',
             'foreign' => 'id'));

        $this->hasOne('Ambitos', array(
             'local' => 'ambitos_id',
             'foreign' => 'id'));

        $this->hasMany('Categorias', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('Clientes', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('Devoluciones', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('PlanificacionMaestros', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('Productos', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('TiendaMaestroPedido', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));

        $this->hasMany('VentasMaestro', array(
             'local' => 'id',
             'foreign' => 'empresas_id'));
    }
}