<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TiendaDetallePlanificacion', 'doctrine');

/**
 * BaseTiendaDetallePlanificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $productos_id
 * @property float $cantidad
 * @property integer $tienda_maestro_planificacion_id
 * @property integer $id
 * @property integer $mes
 * @property integer $ano
 * @property TiendaMaestroPlanificacion $TiendaMaestroPlanificacion
 * @property Productos $Productos
 * 
 * @method integer                    getProductosId()                     Returns the current record's "productos_id" value
 * @method float                      getCantidad()                        Returns the current record's "cantidad" value
 * @method integer                    getTiendaMaestroPlanificacionId()    Returns the current record's "tienda_maestro_planificacion_id" value
 * @method integer                    getId()                              Returns the current record's "id" value
 * @method integer                    getMes()                             Returns the current record's "mes" value
 * @method integer                    getAno()                             Returns the current record's "ano" value
 * @method TiendaMaestroPlanificacion getTiendaMaestroPlanificacion()      Returns the current record's "TiendaMaestroPlanificacion" value
 * @method Productos                  getProductos()                       Returns the current record's "Productos" value
 * @method TiendaDetallePlanificacion setProductosId()                     Sets the current record's "productos_id" value
 * @method TiendaDetallePlanificacion setCantidad()                        Sets the current record's "cantidad" value
 * @method TiendaDetallePlanificacion setTiendaMaestroPlanificacionId()    Sets the current record's "tienda_maestro_planificacion_id" value
 * @method TiendaDetallePlanificacion setId()                              Sets the current record's "id" value
 * @method TiendaDetallePlanificacion setMes()                             Sets the current record's "mes" value
 * @method TiendaDetallePlanificacion setAno()                             Sets the current record's "ano" value
 * @method TiendaDetallePlanificacion setTiendaMaestroPlanificacion()      Sets the current record's "TiendaMaestroPlanificacion" value
 * @method TiendaDetallePlanificacion setProductos()                       Sets the current record's "Productos" value
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiendaDetallePlanificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tienda_detalle_planificacion');
        $this->hasColumn('productos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tienda_maestro_planificacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tienda_detalle_planificacion_id',
             'length' => 4,
             ));
        $this->hasColumn('mes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TiendaMaestroPlanificacion', array(
             'local' => 'tienda_maestro_planificacion_id',
             'foreign' => 'id'));

        $this->hasOne('Productos', array(
             'local' => 'productos_id',
             'foreign' => 'id'));
    }
}