<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PlanificacionDetalles', 'doctrine');

/**
 * BasePlanificacionDetalles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $planificacion_maestros_id
 * @property integer $productos_id
 * @property integer $cantidad
 * @property integer $cantidad_produccion
 * @property integer $dia
 * @property PlanificacionMaestros $PlanificacionMaestros
 * @property Productos $Productos
 * 
 * @method integer               getId()                        Returns the current record's "id" value
 * @method integer               getPlanificacionMaestrosId()   Returns the current record's "planificacion_maestros_id" value
 * @method integer               getProductosId()               Returns the current record's "productos_id" value
 * @method integer               getCantidad()                  Returns the current record's "cantidad" value
 * @method integer               getCantidadProduccion()        Returns the current record's "cantidad_produccion" value
 * @method integer               getDia()                       Returns the current record's "dia" value
 * @method PlanificacionMaestros getPlanificacionMaestros()     Returns the current record's "PlanificacionMaestros" value
 * @method Productos             getProductos()                 Returns the current record's "Productos" value
 * @method PlanificacionDetalles setId()                        Sets the current record's "id" value
 * @method PlanificacionDetalles setPlanificacionMaestrosId()   Sets the current record's "planificacion_maestros_id" value
 * @method PlanificacionDetalles setProductosId()               Sets the current record's "productos_id" value
 * @method PlanificacionDetalles setCantidad()                  Sets the current record's "cantidad" value
 * @method PlanificacionDetalles setCantidadProduccion()        Sets the current record's "cantidad_produccion" value
 * @method PlanificacionDetalles setDia()                       Sets the current record's "dia" value
 * @method PlanificacionDetalles setPlanificacionMaestros()     Sets the current record's "PlanificacionMaestros" value
 * @method PlanificacionDetalles setProductos()                 Sets the current record's "Productos" value
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanificacionDetalles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planificacion_detalles');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'planificacion_detalles_id',
             'length' => 4,
             ));
        $this->hasColumn('planificacion_maestros_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('productos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_produccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('dia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PlanificacionMaestros', array(
             'local' => 'planificacion_maestros_id',
             'foreign' => 'id'));

        $this->hasOne('Productos', array(
             'local' => 'productos_id',
             'foreign' => 'id'));
    }
}