<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PlanificacionMaestros', 'doctrine');

/**
 * BasePlanificacionMaestros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresas_id
 * @property string $mes
 * @property integer $productos_id
 * @property Empresas $Empresas
 * @property Productos $Productos
 * @property Doctrine_Collection $PlanificacionDetalles
 * 
 * @method integer               getId()                    Returns the current record's "id" value
 * @method integer               getEmpresasId()            Returns the current record's "empresas_id" value
 * @method string                getMes()                   Returns the current record's "mes" value
 * @method integer               getProductosId()           Returns the current record's "productos_id" value
 * @method Empresas              getEmpresas()              Returns the current record's "Empresas" value
 * @method Productos             getProductos()             Returns the current record's "Productos" value
 * @method Doctrine_Collection   getPlanificacionDetalles() Returns the current record's "PlanificacionDetalles" collection
 * @method PlanificacionMaestros setId()                    Sets the current record's "id" value
 * @method PlanificacionMaestros setEmpresasId()            Sets the current record's "empresas_id" value
 * @method PlanificacionMaestros setMes()                   Sets the current record's "mes" value
 * @method PlanificacionMaestros setProductosId()           Sets the current record's "productos_id" value
 * @method PlanificacionMaestros setEmpresas()              Sets the current record's "Empresas" value
 * @method PlanificacionMaestros setProductos()             Sets the current record's "Productos" value
 * @method PlanificacionMaestros setPlanificacionDetalles() Sets the current record's "PlanificacionDetalles" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanificacionMaestros extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planificacion_maestros');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'planificacion_maestros_id',
             'length' => 4,
             ));
        $this->hasColumn('empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('mes', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('productos_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresas', array(
             'local' => 'empresas_id',
             'foreign' => 'id'));

        $this->hasOne('Productos', array(
             'local' => 'productos_id',
             'foreign' => 'id'));

        $this->hasMany('PlanificacionDetalles', array(
             'local' => 'id',
             'foreign' => 'planificacion_maestros_id'));
    }
}