<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ambitos', 'doctrine');

/**
 * BaseAmbitos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $coordenada_longitud
 * @property string $coordenada_latitud
 * @property string $tipo_de_ambito_industrial
 * @property string $vias_de_acceso_a_la_fabrica_en_buen_estado
 * @property Doctrine_Collection $Empresas
 * 
 * @method integer             getId()                                         Returns the current record's "id" value
 * @method string              getNombre()                                     Returns the current record's "nombre" value
 * @method string              getCoordenadaLongitud()                         Returns the current record's "coordenada_longitud" value
 * @method string              getCoordenadaLatitud()                          Returns the current record's "coordenada_latitud" value
 * @method string              getTipoDeAmbitoIndustrial()                     Returns the current record's "tipo_de_ambito_industrial" value
 * @method string              getViasDeAccesoALaFabricaEnBuenEstado()         Returns the current record's "vias_de_acceso_a_la_fabrica_en_buen_estado" value
 * @method Doctrine_Collection getEmpresas()                                   Returns the current record's "Empresas" collection
 * @method Ambitos             setId()                                         Sets the current record's "id" value
 * @method Ambitos             setNombre()                                     Sets the current record's "nombre" value
 * @method Ambitos             setCoordenadaLongitud()                         Sets the current record's "coordenada_longitud" value
 * @method Ambitos             setCoordenadaLatitud()                          Sets the current record's "coordenada_latitud" value
 * @method Ambitos             setTipoDeAmbitoIndustrial()                     Sets the current record's "tipo_de_ambito_industrial" value
 * @method Ambitos             setViasDeAccesoALaFabricaEnBuenEstado()         Sets the current record's "vias_de_acceso_a_la_fabrica_en_buen_estado" value
 * @method Ambitos             setEmpresas()                                   Sets the current record's "Empresas" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmbitos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ambitos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'ambitos_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('coordenada_longitud', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('coordenada_latitud', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_de_ambito_industrial', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('vias_de_acceso_a_la_fabrica_en_buen_estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empresas', array(
             'local' => 'id',
             'foreign' => 'ambitos_id'));
    }
}