<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Devoluciones', 'doctrine');

/**
 * BaseDevoluciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ventas_maestro_id
 * @property integer $empresas_id
 * @property integer $cant_devuelta
 * @property VentasMaestro $VentasMaestro
 * @property Empresas $Empresas
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method integer       getVentasMaestroId()   Returns the current record's "ventas_maestro_id" value
 * @method integer       getEmpresasId()        Returns the current record's "empresas_id" value
 * @method integer       getCantDevuelta()      Returns the current record's "cant_devuelta" value
 * @method VentasMaestro getVentasMaestro()     Returns the current record's "VentasMaestro" value
 * @method Empresas      getEmpresas()          Returns the current record's "Empresas" value
 * @method Devoluciones  setId()                Sets the current record's "id" value
 * @method Devoluciones  setVentasMaestroId()   Sets the current record's "ventas_maestro_id" value
 * @method Devoluciones  setEmpresasId()        Sets the current record's "empresas_id" value
 * @method Devoluciones  setCantDevuelta()      Sets the current record's "cant_devuelta" value
 * @method Devoluciones  setVentasMaestro()     Sets the current record's "VentasMaestro" value
 * @method Devoluciones  setEmpresas()          Sets the current record's "Empresas" value
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevoluciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('devoluciones');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'devoluciones_id',
             'length' => 4,
             ));
        $this->hasColumn('ventas_maestro_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cant_devuelta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VentasMaestro', array(
             'local' => 'ventas_maestro_id',
             'foreign' => 'id'));

        $this->hasOne('Empresas', array(
             'local' => 'empresas_id',
             'foreign' => 'id'));
    }
}