<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Municipios', 'doctrine');

/**
 * BaseMunicipios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $nombre
 * @property string $estados_id
 * @property Estados $Estados
 * @property Doctrine_Collection $Parroquias
 * 
 * @method string              getId()         Returns the current record's "id" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getEstadosId()  Returns the current record's "estados_id" value
 * @method Estados             getEstados()    Returns the current record's "Estados" value
 * @method Doctrine_Collection getParroquias() Returns the current record's "Parroquias" collection
 * @method Municipios          setId()         Sets the current record's "id" value
 * @method Municipios          setNombre()     Sets the current record's "nombre" value
 * @method Municipios          setEstadosId()  Sets the current record's "estados_id" value
 * @method Municipios          setEstados()    Sets the current record's "Estados" value
 * @method Municipios          setParroquias() Sets the current record's "Parroquias" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipios');
        $this->hasColumn('id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estados_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estados', array(
             'local' => 'estados_id',
             'foreign' => 'id'));

        $this->hasMany('Parroquias', array(
             'local' => 'id',
             'foreign' => 'municipios_id'));
    }
}