<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clientes', 'doctrine');

/**
 * BaseClientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $tipo_clientes_id
 * @property string $cliente_rif
 * @property integer $empresas_id
 * @property TipoClientes $TipoClientes
 * @property Empresas $Empresas
 * @property Doctrine_Collection $VentasMaestro
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method integer             getTipoClientesId()   Returns the current record's "tipo_clientes_id" value
 * @method string              getClienteRif()       Returns the current record's "cliente_rif" value
 * @method integer             getEmpresasId()       Returns the current record's "empresas_id" value
 * @method TipoClientes        getTipoClientes()     Returns the current record's "TipoClientes" value
 * @method Empresas            getEmpresas()         Returns the current record's "Empresas" value
 * @method Doctrine_Collection getVentasMaestro()    Returns the current record's "VentasMaestro" collection
 * @method Clientes            setId()               Sets the current record's "id" value
 * @method Clientes            setNombre()           Sets the current record's "nombre" value
 * @method Clientes            setTipoClientesId()   Sets the current record's "tipo_clientes_id" value
 * @method Clientes            setClienteRif()       Sets the current record's "cliente_rif" value
 * @method Clientes            setEmpresasId()       Sets the current record's "empresas_id" value
 * @method Clientes            setTipoClientes()     Sets the current record's "TipoClientes" value
 * @method Clientes            setEmpresas()         Sets the current record's "Empresas" value
 * @method Clientes            setVentasMaestro()    Sets the current record's "VentasMaestro" collection
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clientes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'clientes_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_clientes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cliente_rif', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('empresas_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoClientes', array(
             'local' => 'tipo_clientes_id',
             'foreign' => 'id'));

        $this->hasOne('Empresas', array(
             'local' => 'empresas_id',
             'foreign' => 'id'));

        $this->hasMany('VentasMaestro', array(
             'local' => 'id',
             'foreign' => 'clientes_id'));
    }
}