<?php

/**
 * AmbitosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmbitosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AmbitosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ambitos');
    }
}