<?php

/**
 * DevolucionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevolucionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevolucionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Devoluciones');
    }
}