<?php

/**
 * EjesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EjesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EjesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ejes');
    }
}