<?php

/**
 * EstadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estados');
    }
}