<?php

/**
 * ParroquiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParroquiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParroquiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parroquias');
    }
}