<?php

/**
 * PlanificacionDetallesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanificacionDetallesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanificacionDetallesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanificacionDetalles');
    }
}