<?php

/**
 * PlanificacionMaestrosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanificacionMaestrosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanificacionMaestrosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanificacionMaestros');
    }
}