<?php

/**
 * ProductosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Productos');
    }
    
    public static function getPortada()
    {
        $query= Doctrine_Query::create()
                ->select('*')
                ->from('Productos')
                ->limit('5')
                ->execute();
        return $query;
    }
    
    public static function getBusqueda($buscando)
    {
        $query= Doctrine_Query::create()
                ->select('*')
                ->from('Productos')
                ->where('nombre iLIKE ?','%'.$buscando.'%');
        return $query;
    }
}