<?php

/**
 * ProductosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductosTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Productos');
    }

    public static function getPortada() {
        $query = Doctrine_Query::create()
                ->select('p.id, p.nombre, p.denominacion, p.especificaciones, p.presentacion, p.precio_real, p.empresas_id, p.cantidad_inicial, p.categorias_id, max(f.nombre) as foto')
                ->from('Productos p')
                ->innerJoin("p.Foto f")
                ->groupBy('p.id, p.nombre, p.denominacion, p.especificaciones, p.presentacion, p.precio_real, p.empresas_id, p.cantidad_inicial, p.categorias_id')
                ->limit('5')
                ->execute();
        return $query;
    }

    public static function getShow($id) {
        $query = "SELECT p.id, p.nombre, p.denominacion, p.especificaciones, p.presentacion, p.precio_real, p.empresas_id, p.cantidad_inicial, p.categorias_id, f.nombre as foto 
                  FROM Productos p INNER JOIN foto f on f.productos_id=p.id
                  WHERE productos_id =" . $id;
        return Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($query);
    }

    public static function getBusqueda($buscando) {
        $query = Doctrine_Query::create()
                ->select('*')
                ->from('Productos')
                ->where('nombre iLIKE ?', '%' . $buscando . '%');
        return $query;
    }

}