<?php

/**
 * StatusEmpresasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusEmpresasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusEmpresasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusEmpresas');
    }
}