<?php

/**
 * TiendaMaestroPlanificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendaMaestroPlanificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiendaMaestroPlanificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiendaMaestroPlanificacion');
    }
}