<?php

/**
 * TiendaCarritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendaCarritoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TiendaCarritoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('TiendaCarrito');
    }

    public function getComprasUsuario($usuario) {
        $query = Doctrine_Query::create()
                        ->select("producto_id")
                        ->from("TiendaCarrito")
                        ->where("usuario_id=?", $usuario)
                        ->andWhere("activo=?", true)
                        ->execute();
        return $query;
    }

}