<?php

/**
 * TiendaDetallePlanificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendaDetallePlanificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiendaDetallePlanificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiendaDetallePlanificacion');
    }
}