<?php

/**
 * TipoEmpresasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoEmpresasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoEmpresasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoEmpresas');
    }
}