<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tienda_scp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario {
    public static function setSessionVars(){
        $compras=array();
        $comprasActivas=Doctrine_Core::getTable("TiendaCarrito")->getComprasUsuario(1);
        for($i=0;$i<count($comprasActivas);$i++){
            $compras[$i]=$comprasActivas[$i]["producto_id"];
        }
        sfContext::getInstance()->getUser()->setAttribute("compras",$compras);
        return true;
    }
}
