<?php

/**
 * VentasMaestroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentasMaestroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentasMaestroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentasMaestro');
    }
}