# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, jquery-ui-1.8.16.custom.css, ie.css, screen.css, jquery.jqzoom.css, prettyPhoto.css]

  javascripts:    [jquery-1.6.4.min.js, jquery-ui-1.8.16.custom.min.js, main.js, jquery.jqzoom-core.js, jquery.prettyPhoto.js]

  has_layout:     true
  layout:         layout
